-- MySQL Script generated by MySQL Workbench
-- Fri Aug 12 11:48:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema publisher
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema publisher
-- -----------------------------------------------------
drop database if exists publisher;
CREATE SCHEMA IF NOT EXISTS `publisher` DEFAULT CHARACTER SET utf8 ;
USE `publisher` ;

-- -----------------------------------------------------
-- Table `publisher`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publisher`.`author` (
  `a_id` INT NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(45) NOT NULL,
  `cellPhone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `authorcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`a_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publisher`.`book_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publisher`.`book_info` (
  `b_id` INT NOT NULL AUTO_INCREMENT,
  `b_name` VARCHAR(45) NOT NULL,
  `b_price` DECIMAL(5) NOT NULL,
  `b_isbn` VARCHAR(45) NOT NULL,
  `a_id` INT NOT NULL,
  PRIMARY KEY (`b_id`, `b_name`),
  INDEX `fck_x` (`a_id` ASC) VISIBLE,
  CONSTRAINT `fck_bi_a_id`
    FOREIGN KEY (`a_id`)
    REFERENCES `publisher`.`author` (`a_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publisher`.`sales_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publisher`.`sales_info` (
  `si_id` INT NOT NULL AUTO_INCREMENT,
  `b_id` INT NOT NULL,
  `b_name` VARCHAR(45) NOT NULL,
  `s_amount` DECIMAL(5) NOT NULL,
  `s_store` VARCHAR(45) NOT NULL,
  `s_date` DATE NOT NULL,
  PRIMARY KEY (`si_id`),
  -- INDEX `fck_si_b_name_idx` (`b_name` ASC) VISIBLE,
  CONSTRAINT `fck_b_name`
    FOREIGN KEY ( `b_id`, `b_name`)
    REFERENCES `publisher`.`book_info` ( `b_id`, `b_name` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Error Code: 1822. Failed to add the foreign key constraint. 
-- Missing index for constraint 'fck_b_name' in the referenced table 'book_info'	0.000 sec
